/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 07-Jun-2017 19:56:07
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\include\tmwtypes.h 
 */
const int BL = 29;
const real64_T B[29] = {
  -0.005549608069591, -0.02441465590089, -0.01761803676282,   0.0075711197912,
    0.02238052877789,-0.002080458233243, -0.03175457082838,  -0.0107361469078,
     0.0418150385962,  0.03540650319123, -0.05049486292566, -0.08762995174291,
    0.05635874842652,   0.3118930052645,   0.4415904308913,   0.3118930052645,
    0.05635874842652, -0.08762995174291, -0.05049486292566,  0.03540650319123,
     0.0418150385962,  -0.0107361469078, -0.03175457082838,-0.002080458233243,
    0.02238052877789,   0.0075711197912, -0.01761803676282, -0.02441465590089,
  -0.005549608069591
};
